import { Card, Eyebrow, Section, Shell, SecondaryButton } from '@/components/ui/primitives';
import { galleryItems } from '@/lib/data';

export default function AboutPage() {
  return (
    <main>
      <Section className="border-b border-white/10 bg-black/30 pt-24"><Shell className="space-y-5"><Eyebrow>About Aurelio House</Eyebrow><h1 className="max-w-4xl font-display text-5xl leading-none md:text-7xl">Built around hospitality that feels composed, warm, and exacting.</h1><p className="max-w-3xl text-lg text-mist">Every element, from the menu structure to the room lighting, is calibrated to help guests settle into an evening worth remembering.</p></Shell></Section>
      <Section><Shell className="grid gap-8 lg:grid-cols-2"><div className="space-y-4"><Eyebrow>Brand story</Eyebrow><h2 className="font-display text-4xl">From intimate supper clubs to a landmark dining address.</h2><p className="text-mist">Aurelio House began as a chef-led series of private dinners for guests who wanted restaurant-grade craft in a more intimate, more thoughtful setting. That same attention now defines the full restaurant experience.</p><p className="text-mist">Today, the house is known for seasonal fire-led menus, sommelier pairings, and service shaped around quiet confidence rather than spectacle.</p></div><div className="grid gap-4 md:grid-cols-2"><div className="min-h-[420px] rounded-[28px] border border-white/10 bg-[linear-gradient(145deg,rgba(226,192,137,0.14),transparent_45%),linear-gradient(135deg,#231913_0%,#11141a_100%)]" /><div className="grid gap-4"><div className="min-h-[200px] rounded-[28px] border border-white/10 bg-[linear-gradient(135deg,#241c16_0%,#3d3026_100%)]" /><div className="min-h-[200px] rounded-[28px] border border-white/10 bg-[linear-gradient(135deg,#0f1218_0%,#2c2019_100%)]" /></div></div></Shell></Section>
      <Section className="bg-white/5"><Shell><div className="mb-8 space-y-3"><Eyebrow>Mission & values</Eyebrow><h2 className="font-display text-4xl">A premium restaurant should feel effortless for the guest and disciplined behind the scenes.</h2></div><div className="grid gap-5 md:grid-cols-4">{[['Ingredient integrity','Menus are built around produce at its peak and proteins sourced for flavor rather than volume.'],['Measured hospitality','Our team reads the room, respects pacing, and serves with quiet confidence.'],['Design-led comfort','Material warmth, balanced acoustics, and cinematic lighting shape the tone of each evening.'],['Consistency','Luxury is proven through reliability across service, flavor, and detail.']].map(([title, copy]) => <Card key={title} className="p-6"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 text-sm text-mist">{copy}</p></Card>)}</div></Shell></Section>
      <Section><Shell className="grid gap-8 lg:grid-cols-2"><Card className="min-h-[360px] p-8"><Eyebrow>Founder & Executive Chef</Eyebrow><h3 className="mt-4 text-3xl font-semibold">Luca Moretti</h3><p className="mt-4 text-mist">Trained across Milan and Copenhagen, Chef Luca combines European finesse with charcoal-driven depth, building menus that feel both current and enduring.</p></Card><div className="space-y-4"><Eyebrow>Chef & founder</Eyebrow><h2 className="font-display text-4xl">Leadership shaped by precision and restraint.</h2><p className="text-mist">Chef Luca leads a team that values prep discipline, respectful sourcing, and service that feels present without intrusion.</p><div className="grid gap-4">{[['Hospitality-led training','Every guest-facing touchpoint is rehearsed for warmth, clarity, and consistency.'],['Seasonal R&D','New dishes are prototyped monthly with a focus on texture, aroma, and pacing.']].map(([title, copy]) => <Card key={title} className="p-5"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 text-sm text-mist">{copy}</p></Card>)}</div></div></Shell></Section>
      <Section className="bg-black/30"><Shell className="grid gap-8 lg:grid-cols-2"><div className="space-y-4"><Eyebrow>Atmosphere</Eyebrow><h2 className="font-display text-4xl">An evening environment designed as carefully as the plates.</h2><p className="text-mist">Walnut, brushed brass, leather banquettes, and layered lighting create a room that feels intimate even at full energy.</p><SecondaryButton href="/reservation">Reserve the room</SecondaryButton></div><div className="grid gap-4 md:grid-cols-2">{galleryItems.slice(0,4).map((item) => <Card key={item} className="flex min-h-[220px] items-end p-5 bg-[linear-gradient(145deg,rgba(226,192,137,0.14),transparent_45%),linear-gradient(135deg,#101319_0%,#2a1d16_100%)]"><div><Eyebrow>Interior</Eyebrow><div className="mt-2 font-display text-2xl">{item}</div></div></Card>)}</div></Shell></Section>
      <Section><Shell><div className="mb-8 space-y-3"><Eyebrow>Recognition</Eyebrow><h2 className="font-display text-4xl">Awards, press mentions, and signals of trust.</h2></div><div className="grid gap-5 md:grid-cols-4">{['Best New Dining Room','2 Forks Distinction','Sommelier\'s Cellar List','Guest Choice 2025'].map((award) => <Card key={award} className="p-6"><h3 className="text-xl font-semibold">{award}</h3><p className="mt-3 text-sm text-mist">Recognized by hospitality and dining publications.</p></Card>)}</div></Shell></Section>
    </main>
  );
}

